batch_size = 104
do_profile = false
num_epochs = 150

[data]
data_batch_size = 52
raw_data_folder = "data"
data_folder = "precomputed"
train_split = 8
test_split = 3
valid_split = 3
do_augment = false

[train]
max_grad_norm = 2.0
weight_decay = 0.03
start_lr_frac = 0.5

[train.loss]
loss_delta = 0.2
use_rmse = false

[log]
exp_name = 'e_form_simple'

[vit.head.activation]
name = 'swish'

[vit.vit_input]
patch_size = 3
patch_latent_dim = 256

[vit.downsample]
factor = []
channels_out = []
kernel_size = []

[vit.encoder]
num_layers = 2
num_heads = 4
enc_attention_dropout_rate = 0.2
enc_dropout_rate = 0.2

[vit.encoder.mlp]
dropout = 0.2

[vit.encoder.mlp.activation]
name = 'swish'

[vit.species_embed]
species_embed_dim = 64
use_simple_weighting = true

[vit.species_embed.spec_embed]
out_dim = 64

[vit.species_embed.spec_embed.activation]
name = 'swish'
