batch_size = 52
do_profile = false
num_epochs = 4

[data]
train_split = 2
test_split = 23
valid_split = 1

[cli]
verbosity = "info"
show_progress = true

[device]
device = "gpu"
max_gpus = 1

[log]
exp_name = 'smoke_test'
